export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const CLEAR_EMPLOYEE = 'CLEAR_EMPLOYEE';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEW = 'GET_REVIEW';
export const REVIEW_ERROR = 'REVIEW_ERROR';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const ADD_REVIEW = 'ADD_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const CLEAR_REVIEW = 'CLEAR_REVIEW';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const REMOVE_FEEDBACK = 'REMOVE_FEEDBACK';
